development: &local
    site_name: Eventbrite Clone
    site_url: http://cherrytickets.com/
    app_url: http://cherrytickets.com/eventdemo/app/assets/images/
    js_url: http://cherrytickets.com/eventdemo/app/assets/javascripts/
    css_url: http://cherrytickets.com/eventdemo/app/assets/stylesheets/
    upload_url: http://cherrytickets.com/eventdemo/public/
    folder: eventdemo
    
production:
  <<: *local

staging:
  <<: *local

test:
  <<: *local